# --- BLOC DE DÉFINITION DE GROUPE ET HÔTE ---
# Déclare le groupe de machines nommé "graylog" et y liste le conteneur cible (graylog-lxc).
[graylog]
graylog-lxc

# --- BLOC DES VARIABLES DE GROUPE (VARS) ---
# Centralise toutes les configurations de connexion et d'authentification pour le groupe.
[graylog:vars]
# Indique à Ansible d'utiliser le connecteur natif Proxmox (PCT) pour administrer le conteneur depuis l'hôte, sans passer par le SSH interne du LXC.
ansible_connection=community.proxmox.proxmox_pct_remote

# Récupération dynamique via l'environnement (lookup env) des accès de l'hyperviseur Proxmox et de l'ID spécifique du conteneur Graylog.
ansible_host={{ lookup('env', 'PROXMOX_HOST') }}
ansible_user=terraform
ansible_password={{ lookup('env', 'PROXMOX_SSH_PASSWORD') }}
proxmox_vmid={{ lookup('env', 'GRAYLOG_VMID') }}

# Sécurisation réseau : ignore la validation de l'empreinte de la clé SSH lors de la connexion initiale au serveur Proxmox.
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
