# --- BLOC DE DÉFINITION DE GROUPE ET HÔTE ---
# Déclare le groupe de machines nommé "nextcloud" et y liste le conteneur cible (nextcloud-lxc).
[nextcloud]
nextcloud-lxc

# --- BLOC DES VARIABLES DE GROUPE (VARS) ---
# Regroupe l'ensemble des paramètres de connexion et d'authentification requis pour ce groupe.
[nextcloud:vars]
# Indique à Ansible d'interagir avec le conteneur via l'API Proxmox (PCT remote) au lieu d'ouvrir un accès SSH classique à l'intérieur du LXC.
ansible_connection=community.proxmox.proxmox_pct_remote

# Extraction dynamique des variables d'environnement système (lookup env) pour cibler l'hyperviseur Proxmox et spécifier l'ID du conteneur Nextcloud.
ansible_host={{ lookup('env', 'PROXMOX_HOST') }}
ansible_user=terraform
ansible_password={{ lookup('env', 'PROXMOX_SSH_PASSWORD') }}
proxmox_vmid={{ lookup('env', 'NEXTCLOUD_VMID') }}

# Configuration de sécurité SSH : ignore la validation de l'empreinte de la clé lors de la première connexion à l'hôte Proxmox.
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
