# -- BLOC DE DÉFINITION DE GROUPE ET HÔTE ---
# Déclare le groupe de machines nommé "nagios" et y liste la cible (le conteneur nagios-lxc).
[nagios]
nagios-lxc

# --- BLOC DES VARIABLES DE GROUPE (VARS) ---
# Définit l'ensemble des paramètres d'accès et d'authentification pour toutes les machines du groupe.
[nagios:vars]
# Spécifie à Ansible d'utiliser le connecteur Proxmox pour piloter le conteneur directement depuis l'hôte (PCT) au lieu de passer par une connexion SSH classique dans le conteneur.
ansible_connection=community.proxmox.proxmox_pct_remote

# Récupération dynamique via le système (lookup env) des variables d'environnement pour l'hôte Proxmox, les accès de l'utilisateur Terraform et l'ID du conteneur cible.
ansible_host={{ lookup('env', 'PROXMOX_HOST') }}
ansible_user=terraform
ansible_password={{ lookup('env', 'PROXMOX_SSH_PASSWORD') }}
proxmox_vmid={{ lookup('env', 'NAGIOS_VMID') }}

# Sécurisation réseau : désactive la validation stricte de l'empreinte de la clé SSH lors de la connexion initiale à l'hyperviseur.
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
