# --- BLOC DE DÉFINITION DE GROUPE ET HÔTE ---
# Déclare le groupe de machines nommé "mariadb" et y liste le conteneur cible (mariadb-lxc).
[mariadb]
mariadb-lxc

# --- BLOC DES VARIABLES DE GROUPE (VARS) ---
# Regroupe tous les paramètres de connexion et d'authentification applicables à ce groupe.
[mariadb:vars]
# Force Ansible à utiliser le plugin Proxmox (PCT) pour exécuter les commandes directement depuis l'hôte hôte, sans dépendre du SSH interne du LXC.
ansible_connection=community.proxmox.proxmox_pct_remote

# Récupération dynamique depuis l'environnement (lookup env) des accès de l'hyperviseur Proxmox et de l'ID unique de ce conteneur MariaDB.
ansible_host={{ lookup('env', 'PROXMOX_HOST') }}
ansible_user=terraform
ansible_password={{ lookup('env', 'PROXMOX_SSH_PASSWORD') }}
proxmox_vmid={{ lookup('env', 'MARIADB_VMID') }}

# Gestion SSH : désactive la validation stricte de l'empreinte de la clé de l'hôte Proxmox lors de la connexion initiale.
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
